---
- name: Install dev tools
  ansible.builtin.apt:
    name:
      - fish
      - neovim
      - sysstat
      - btop

- name: Install alp
  ansible.builtin.get_url:
    url: https://github.com/tkuchiki/alp/releases/download/v1.0.21/alp_linux_amd64.tar.gz
    dest: /tmp/alp.tar.gz

- name: Unarchive alp
  ansible.builtin.unarchive:
    src: /tmp/alp.tar.gz
    dest: /usr/local/bin
    remote_src: true

- name: Copy isualp.sh
  ansible.builtin.copy:
    src: isualp.sh
    dest: /usr/local/bin/isualp.sh
    owner: root
    group: root
    mode: "0755"

- name: Copy mysqldumpslow.sh
  ansible.builtin.copy:
    src: mysqldumpslow.sh
    dest: /usr/local/bin/mysqldumpslow.sh
    owner: root
    group: root
    mode: "0755"
